# This workflow will install Octave and run unit tests and the demos

name: Octave application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y octave octave-statistics
    - name: Run unit tests
      run: |
        pushd tests
        octave test_distanceMatrix.m
        octave test_PCA.m
        octave test_kernel.m
        octave test_kPCA.m
        octave test_extensions.m
        octave test_stability.m
        octave test_reconstruction.m
        popd
    - name: Run demo1
      run: |
        pushd demo1
        octave demo_SyntheticData.m
        popd
    - name: Run demo2
      run: |
        pushd demo2
        octave demo_YaleFace.m
        popd
    - name: Run demo3
      run: |
        pushd demo3
        octave demo_faceASM_PCA.m
        octave demo_faceASM_kPCA.m
        popd
   